### ISSUE TITLE
[BUG] Docker - Permission denied

### ISSUE THREAD

**Issue by modem7** [Boerderij/Varken#178]
**Describe the bug**
When initially deploying Varken in docker I get the following message:

GF_PATHS_DATA='/config/data' is not writable.

You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later

mkdir: can't create directory '/config/plugins': Permission denied

**To Reproduce**
1. Created Varken docker image from docker compose listed in repo
2. Attempted to add User: "472" as per link above

**Expected behavior**
Permissions allowed

**Screenshots**

**Environment (please complete the following information):**
 - OS: Latest Docker tag

**Additional context**

```
  grafana:
    hostname: Grafana
    container_name: Grafana
    image: grafana/grafana
    networks:
      pihole:
        ipv4_address: '172.22.0.115'
    ports:
      - 3001:3000
    user: "472"
    volumes: 
      - Grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - TZ=Europe/London
    depends_on:
      - varkendb
      - varken
    restart: unless-stopped
```
