### ISSUE TITLE
[Feature Request] Overseerr support

### ISSUE THREAD

**Issue by 19wolf** [Boerderij/Varken#189]
[Overseerr](https://github.com/sct/overseerr) is a new alternative to Ombi, and should be supported by Varken.

**Comment by samwiseg0** [comment]
I agree. I would like to see where the project goes. I will see if I can work on it in the near future. The developer has been inundated with new folks.

**Comment by Maxtoid** [comment]
I too would very much love Overseerr support for this if possible at some point. After years on Ombi, I have cutover my production requests system to Overseerr as it is so stable and SO much better all around than Ombi.

**Comment by redredbeard** [comment]
Added support in a pull request - https://github.com/Boerderij/Varken/pull/210

**Comment by samwiseg0** [comment]
Overseer support has been added in develop. Please test and let us know if there are any issues.

**Comment by a351must2** [comment]
I just installed the development version yesterday and added an Overseerr configuration.  I don't see any errors about Overseerr in the logs, and plenty of "WARNING : overseerr : No data to send to influx for overseerr-latest-requests instance, discarding."  Most likely due to no new requests, but there was a couple new requests yesterday and some requests completed yesterday. 

So far I don't see an "Overseerr" table in the database.  Just Ombi and the other configured services.

**Comment by modem7** [comment]
> I just installed the development version yesterday and added an Overseerr configuration. I don't see any errors about Overseerr in the logs, and plenty of "WARNING : overseerr : No data to send to influx for overseerr-latest-requests instance, discarding." Most likely due to no new requests, but there was a couple new requests yesterday and some requests completed yesterday.
> 
> So far I don't see an "Overseerr" table in the database. Just Ombi and the other configured services.

I've just done the same, but got it working. 

Here's my compose file snippet:

```yaml
  # Varken - Application to aggregate data from the Plex ecosystem
  varken:
    hostname: varken
    container_name: Varken
    image: boerderij/varken:develop
    networks:
      - isonet
      - isolated
    volumes:
      - $USERDIR/TIGVStack/Varken:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - VRKN_GLOBAL_SONARR_SERVER_IDS=$VRKN_GLOBAL_SONARR_SERVER_IDS
      - VRKN_GLOBAL_RADARR_SERVER_IDS=$VRKN_GLOBAL_RADARR_SERVER_IDS
      - VRKN_GLOBAL_LIDARR_SERVER_IDS=$VRKN_GLOBAL_LIDARR_SERVER_IDS
      - VRKN_GLOBAL_TAUTULLI_SERVER_IDS=$VRKN_GLOBAL_TAUTULLI_SERVER_IDS
      - VRKN_GLOBAL_OMBI_SERVER_IDS=$VRKN_GLOBAL_OMBI_SERVER_IDS
      - VRKN_GLOBAL_SICKCHILL_SERVER_IDS=$VRKN_GLOBAL_SICKCHILL_SERVER_IDS
      - VRKN_GLOBAL_MAXMIND_LICENSE_KEY=$VRKN_GLOBAL_MAXMIND_LICENSE_KEY
      - VRKN_INFLUXDB_URL=$VRKN_INFLUXDB_URL
      - VRKN_INFLUXDB_PORT=$VRKN_INFLUXDB_PORT
      - VRKN_INFLUXDB_SSL=$VRKN_INFLUXDB_SSL
      - VRKN_INFLUXDB_VERIFY_SSL=VRKN_INFLUXDB_VERIFY_SSL
      - VRKN_INFLUXDB_USERNAME=$VRKN_INFLUXDB_USERNAME
      - VRKN_INFLUXDB_PASSWORD=VRKN_INFLUXDB_PASSWORD
      ~~Other variables not relevant to Overseer~~
      - VRKN_OVERSEERR_1_URL=$VRKN_OVERSEERR_1_URL
      - VRKN_OVERSEERR_1_APIKEY=$VRKN_OVERSEERR_1_APIKEY
      - VRKN_OVERSEERR_1_SSL=$VRKN_OVERSEERR_1_SSL
      - VRKN_OVERSEERR_1_VERIFY_SSL=$VRKN_OVERSEERR_1_VERIFY_SSL
      - VRKN_OVERSEERR_1_GET_REQUEST_TOTAL_COUNTS=$VRKN_OVERSEERR_1_GET_REQUEST_TOTAL_COUNTS
      - VRKN_OVERSEERR_1_REQUEST_TOTAL_RUN_SECONDS=$VRKN_OVERSEERR_1_REQUEST_TOTAL_RUN_SECONDS
      - VRKN_OVERSEERR_1_GET_LATEST_REQUESTS_TO_FETCH=$VRKN_OVERSEERR_1_GET_LATEST_REQUESTS_TO_FETCH
      - VRKN_OVERSEERR_1_NUM_LATEST_REQUESTS_SECONDS=$VRKN_OVERSEERR_1_NUM_LATEST_REQUESTS_SECONDS
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    # labels:
    #   - backup
    depends_on:
      - influxdb
    restart: always
```

And you'll need to change values in Grafana as well. I just modified the Ombi ones. 

![image](https://user-images.githubusercontent.com/4349962/160711208-b3ce0e1a-6dc8-4558-a9c9-af0a6514489f.png)

Be aware that there seems to be a typo [here](https://github.com/Boerderij/Varken/commit/a60e41e6e4c9206473ae02855f65321a8adbfb5a#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R109) which may cause issues. It seems that it should be `SECONDS` not `SECONDSS`. Might be one for @samwiseg0 to address. 

(Also [this](https://github.com/Boerderij/Varken/commit/a60e41e6e4c9206473ae02855f65321a8adbfb5a#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R104) probably needs renaming to `overseer.domain.ltd`)
